name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- FRONTEND ----------
      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install frontend dependencies
        working-directory: ./FrontZurich/front-zurich
        run: npm install

      - name: Build frontend
        working-directory: ./FrontZurich/front-zurich
        run: |
            npm ci
            npm run build -- --base-href /zurich_test/
            cp dist/front-zurich/index.html dist/front-zurich/404.html
        
      - name: Artifact upload
        uses: actions/upload-pages-artifact@v4
        with: 
          name: github-pages
          path: ./FrontZurich/front-zurich/dist/front-zurich
        
  deploy: 
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github
        id: deployment
        uses: actions/deploy-pages@v4
